SET SEARCH_PATH = gov;
CREATE OR REPLACE FUNCTION fnc_gen_protocol(p_alpha2 VARCHAR(2))
RETURNS TEXT AS 
	$BODY$
BEGIN
	--RETURN p_alpha2 || TO_CHAR(CLOCK_TIMESTAMP(), 'YYMMDDHH24MISS') || RIGHT(RANDOM()::TEXT,2) ;
	RETURN p_alpha2 || TO_CHAR(CLOCK_TIMESTAMP(), 'YYMMDD') || LPAD(NEXTVAL('protocol_seq')::TEXT, 4, '0') ||  RIGHT(RANDOM()::TEXT,2);
END;
$BODY$
LANGUAGE plpgsql;

